version: '3'

services:
  postgres-1:
    image: bitnami/postgresql-repmgr:latest
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=cuba
      - POSTGRESQL_USERNAME=cuba
      - POSTGRESQL_PASSWORD=cuba
      - POSTGRESQL_DATABASE=cuba
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgres-1
      - REPMGR_PARTNER_NODES=postgres-1,postgres-2
      - REPMGR_NODE_NAME=postgres-1
      - REPMGR_NODE_NETWORK_NAME=postgres-1
  postgres-2:
    image: bitnami/postgresql-repmgr:latest
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=cuba
      - POSTGRESQL_USERNAME=cuba
      - POSTGRESQL_PASSWORD=cuba
      - POSTGRESQL_DATABASE=cuba
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=postgres-1
      - REPMGR_PARTNER_NODES=postgres-1,postgres-2
      - REPMGR_NODE_NAME=postgres-2
      - REPMGR_NODE_NETWORK_NAME=postgres-2
  postgres:
    depends_on:
      - postgres-1
      - postgres-2
    image: bitnami/pgpool:latest
    environment:
      - PGPOOL_BACKEND_NODES=0:postgres-1:5432,1:postgres-2:5432
      - PGPOOL_SR_CHECK_USER=cuba
      - PGPOOL_SR_CHECK_PASSWORD=cuba
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=cuba
      - PGPOOL_POSTGRES_PASSWORD=cuba
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=cuba
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: zookeeper
  core_1:
    depends_on:
      - postgres
    image: planner-core:latest
    environment:
      - CUBA_WEBAPPURL=http://abelyaev/planner
      - CUBA_WEBHOSTNAME=core_1
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
      - JGROUPS_BIND_ADDR=core_1
  core_2:
    depends_on:
      - postgres
    image: planner-core:latest
    environment:
      - CUBA_WEBAPPURL=http://abelyaev/planner
      - CUBA_WEBHOSTNAME=core_2
      - CUBA_TRUSTEDCLIENTPERMITTEDIPLIST=*.*.*.*
      - JGROUPS_BIND_ADDR=core_2
  web_1:
    image: planner:latest
    environment:
     - CUBA_CONNECTIONURLLIST=http://core_1:8079/planner-core, http://core_2:8079/planner-core
     - CUBA_WEBHOSTNAME=abelyaev
     - CUBA_WEBAPPURL=http://abelyaev/planner
  web_2:
    image: planner:latest
    environment:
      - CUBA_CONNECTIONURLLIST=http://core_1:8079/planner-core, http://core_2:8079/planner-core
      - CUBA_WEBHOSTNAME=abelyaev
      - CUBA_WEBAPPURL=http://abelyaev/planner
  nginx:
    depends_on:
      - web_1
      - web_2
    image: nginx:latest
    volumes:
    - "c:/demo/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
    - "80:80"