version: '2'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=cuba
      - POSTGRES_USER=cuba
      - POSTGRES_PASSWORD=cuba
    ports:
      - "5432:5432"
  web:
    depends_on:
      - postgres
    image: planner:jdk11
    volumes:
      - /quickstart/planner-home:/opt/planner-home
    ports:
      - "5000:5000"
