-- begin SESSIONPLANNER_SPEAKER
create unique index IDX_SESSIONPLANNER_SPEAKER_UNIQ_EMAIL on SESSIONPLANNER_SPEAKER (EMAIL)^
create index IDX_SESSIONPLANNER_SPEAKER_LAST_NAME on SESSIONPLANNER_SPEAKER (LAST_NAME)^
-- end SESSIONPLANNER_SPEAKER
-- begin SESSIONPLANNER_SESSION
alter table SESSIONPLANNER_SESSION add constraint FK_SESSIONPLANNER_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references SESSIONPLANNER_SPEAKER(ID)^
create index IDX_SESSIONPLANNER_SESSION_ON_SPEAKER on SESSIONPLANNER_SESSION (SPEAKER_ID)^
-- end SESSIONPLANNER_SESSION
