FROM tomcat:9-jdk11

#Removing default applications like manager
ENV DEPLOY_DIR $CATALINA_HOME/webapps/
RUN rm -rf $DEPLOY_DIR/*

#Preparing default app home folder
RUN mkdir $DEPLOY_DIR/planner-home

#Setting environment variables
ENV spring.profiles.active=docker
ENV app.home=$DEPLOY_DIR/planner-home

#Deploying applications to tomcat
COPY planner.war $DEPLOY_DIR
COPY planner-core.war $DEPLOY_DIR
