-- begin SESSIONPLANNER_SPEAKER
alter table SESSIONPLANNER_SPEAKER add constraint FK_SESSIONPLANNER_SPEAKER_ON_PHOTO foreign key (PHOTO_ID) references SYS_FILE(ID)^
create unique index IDX_SESSIONPLANNER_SPEAKER_UK_EMAIL on SESSIONPLANNER_SPEAKER (EMAIL) where DELETE_TS is null ^
create index IDX_SESSIONPLANNER_SPEAKER_ON_PHOTO on SESSIONPLANNER_SPEAKER (PHOTO_ID)^
-- end SESSIONPLANNER_SPEAKER
-- begin SESSIONPLANNER_SESSION
alter table SESSIONPLANNER_SESSION add constraint FK_SESSIONPLANNER_SESSION_ON_SPEAKER foreign key (SPEAKER_ID) references SESSIONPLANNER_SPEAKER(ID)^
create index IDX_SESSIONPLANNER_SESSION_ON_SPEAKER on SESSIONPLANNER_SESSION (SPEAKER_ID)^
-- end SESSIONPLANNER_SESSION
